name: Multi-Arch Docker Build and Push

on:
  push:
    branches:
      - main
      - master

jobs:
  docker:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      #- name: Setup QEMU
      #  uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        run: |
          docker buildx inspect

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3



          
      - name: Build & Push Multi-Arch Image
        run: |
          IMAGE_NAME=/${{ github.repository }}
          COMMIT=${{ github.sha }}
          echo "Repo: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:$COMMIT \
            --push .
